language: ruby
rvm:
- 2.3.3

before_script: 
 - chmod +x ./script/cibuild

script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master
  - gh-pages
  - /pages-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

exclude: [vendor]

sudo: false