# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: That's a Bug!
email: jgfarias42@gmail.com
description: >
  My name is João Farias; if you read the lines on this blog, you will find out
  how to write (and how not to, mainly) write the right software right through
  hardcore testing.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: JFThatsABug
github_username:  JoaoGFarias

timezone: America/Recife

plugins:
  - jekyll-gist
  - jekyll-paginate

deploy:
      host: github_pages
      branch: master

pages_list:
  Archive: '/archive'
  Feed: '/feed.xml'

# Build settings
markdown: kramdown
