# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: That's a Bug!
email: joao@thatsabug.com
description:
  Writing the software the right way through hardcore testing.
long_description:
  My name is João Farias; if you read the lines on this blog, you will find out
  how to write (and how not to, mainly) software the right way through
  hardcore testing.

url: "https://thatsabug.com/"
footer_links:
  email:
    joao@thatsabug.com
  linkedin:
    username:  
      joaogfarias
  github:
    username: 
      JoaoGFarias
  twitter:
    username:
      JFThatsABug
    card: 
      summary
social:
  links:
    - https://github.com/JoaoGFarias
    - https://twitter.com/JFThatsABug
    - https://www.linkedin.com/in/joaogfarias/

timezone: America/Recife

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

deploy:
      host: github_pages
      branch: master

pages_list:
  Archive: '/archive'
  Feed: '/feed.xml'

# Build settings
markdown: kramdown

